import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import BG from "@/components/bg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ colorScheme: "system" }}>
      {/* FIXME: remove on prod */}
      {process.env.NODE_ENV === "development" ? (
        <script async src="https://cdn.tailwindcss.com"></script>
      ) : undefined}
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <BG>{children}</BG>
        </ThemeProvider>
      </body>
    </html>
  );
}
